Update prompt

diff --git a/bin/cdw b/bin/cdw
--- a/bin/cdw
+++ b/bin/cdw
@@ -4,30 +4,30 @@
 # Description: Change directory using Windows path
 # Example: cdw C:\Users\Username\Documents
 
-# Check if wlspath is available
-if ! command -v wslpath &>/dev/null; then
-	echo "wslpath command not found"
-	return 1
-fi
-# Check if $1 is -h or --help
-if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
-	echo "Usage: cdw <windows_path>"
-	return 0
-fi
-if [ -z "$1" ]; then
-	1="C:/"
-fi
-# Check if the path is a well formed Windows path
-if ! echo "$1" | grep -qE '^[A-Za-z]:[/|\\]'; then
-	echo "Invalid Windows path: $1"
-	return 1
-fi
-# Convert Windows path to WSL path
-local linux_path=$(wslpath -u "$1")
-if [ -z "$linux_path" ]; then
-	echo "Invalid Windows path: $1"
-	return 1
-fi
+cdw() {
+	# Check if wlspath is available
+	if ! command -v wslpath &>/dev/null; then
+		echo "wslpath command not found"
+	fi
+	# Check if $1 is -h or --help
+	if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
+		echo "Usage: cdw <windows_path>"
+	fi
 
-cd "$linux_path"
-return $?
+	if [ -z "$1" ]; then
+		1="C:/"
+	fi
+	# Check if the path is a well formed Windows path
+	if ! echo "$1" | grep -qE '^[A-Za-z]:[/|\\]'; then
+		echo "Invalid Windows path: $1"
+	fi
+	# Convert Windows path to WSL path
+	linux_path=$(wslpath -u "$1")
+	if [ -z "$linux_path" ]; then
+		echo "Invalid Windows path: $1"
+	fi
+
+	# Change directory to the WSL path
+	cd "$linux_path"
+	echo "$linux_path"
+}
