Format code with `shfmt`

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -26,10 +26,20 @@ fail() {
 }
 
 set_zsh_as_default_shell() {
-	echo -n 'Do you want to set ZSH as the default shell? Root access is required. (y/n) '
-	read -n 1 action
+	# Check if ZSH is installed and if it is the default shell
+	if ! command -v zsh >/dev/null 2>&1; then
+		fail 'ZSH is not installed! ~/.dotfiles/script/install.sh has to be run before ~/.dotfiles/script/boostrap.sh'
+	fi
+
+	# Check if ZSH is the default shell
+	if [[ $SHELL == $(which zsh) ]]; then
+		return
+	fi
+
+	echo -n 'Do you want to set ZSH as the default shell? Root access is required. (y/N) '
+	read action
 	echo ''
-	if [[ $action != "y" && $action != "Y" ]]; then
+	if [[ ${action:0:1} != "y" && ${action:0:1} != "Y" ]]; then
 		return
 	fi
 	# Set ZSH as the default shell
